#!/bin/sh

# Control variable
# Possible values: NONE, FULL, LOW, CRITICAL
last="NONE"

# Default values for LOW/CRITICAL status
low=15
critical=10
danger=5

while true; do

  # If battery is plugged, do stuff
  battery="/sys/class/power_supply/BAT0"
  if [ -d $battery ]; then

    capacity=$(cat $battery/capacity)
    status=$(cat $battery/status)

    # If battery full and not already warned about that
    if [ "$last" != "FULL" ] && [ "$status" = "Full" ]; then
      notify-send "Battery full"
      last="FULL"
    fi

    # If low and discharging
    if [ "$last" != "LOW" ] && [ "$status" = "Discharging" ] && \
       [ $capacity -le $low ]; then
      notify-send "Battery low: $capacity%"
      last=LOW
    fi

    # If critical and discharging
    if ["$last" != "CRITICAL"] && [ "$status" = "Discharging" ] && \
      [ $capacity -le $critical ]; then
      notify-send -u critical "Battery very low: $capacity%"
      last=CRITICAL
    fi

    # If danger and discharging
    if [ "$status" = "Discharging" ] && [ $capacity -le $danger ]; then
      notify-send -u critical "Battery very low: $capacity%" "Shutting Down in 60 seconds!"
      sleep 60
      shutdown -h now
      last=DANGER
    fi

  fi
  sleep 60
done
